"""candid sync — file-based machine-to-machine sync (no cloud).

A sync *bundle* is a plain zip file you move yourself (USB drive, AirDrop,
shared folder, whatever you trust). It carries a manifest with per-file
sha256 checksums, a format version, and the source machine id.

Submodules (each owned by a different batch-74 worker; add new files only,
do not edit this file):
    machine     stable per-machine id
    categories  data categories <-> relative paths under DATA_DIR
    manifest    manifest schema, checksum helpers
    errors      SyncError
    bundle      export bundles (worker A)
    importer    import bundles with dry-run (worker B)
    merge       three-way merge engine (worker C)
    conflicts   conflict listing/resolution (worker C)
    delta       incremental bundles + base snapshots (worker D)
    history     sync log + status (worker D)
    pairing     peer pairing bootstrap (worker E)
    rules       auto-resolve rules (worker E)

Sync state lives under DATA_DIR / "sync" (git-ignored with candid_data/).
"""
