#!/usr/bin/env python3
"""Generate per-command reference docs from the argparse parser.

Offline and idempotent: walks the parser built by candid.__main__.build_parser
and writes candid/data/docs/commands/<command>.md for every command in
candid.__main__.COMMANDS. Each page carries a usage line, the command
description, its subcommands (with their own usage and options), and an
options table. Running this twice produces byte-identical files.

Usage:
    python3 scripts/gen_command_docs.py
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from candid.__main__ import COMMANDS, build_parser  # noqa: E402

OUT_DIR = REPO_ROOT / "candid" / "data" / "docs" / "commands"
GENERATED_NOTE = "<!-- GENERATED by scripts/gen_command_docs.py - do not edit by hand. -->"


def _subparsers_action(parser: argparse.ArgumentParser):
    """Return the _SubParsersAction of a parser, or None."""
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _choice_help(sub_action: argparse._SubParsersAction, name: str) -> str:
    for action in sub_action._choices_actions:
        if action.dest == name:
            return action.help or ""
    return ""


def _usage(parser: argparse.ArgumentParser) -> str:
    """Single-line usage string (argparse wraps; collapse whitespace)."""
    return re.sub(r"\s+", " ", parser.format_usage().strip())


def _option_rows(parser: argparse.ArgumentParser) -> list[tuple[str, str]]:
    """(display, description) rows for a parser's own options."""
    rows = []
    for action in parser._actions:
        if isinstance(action, (argparse._HelpAction,
                               argparse._VersionAction,
                               argparse._SubParsersAction)):
            continue
        if action.option_strings:
            display = ", ".join(f"`{o}`" for o in action.option_strings)
            if isinstance(action, (argparse._StoreAction, argparse._AppendAction)):
                metavar = action.metavar or action.dest.upper()
                display += f" `{metavar}`"
        else:
            display = f"`{action.dest}`"  # positional
        desc = (action.help or "").strip()
        default = action.default
        if (default not in (None, False, "", [], argparse.SUPPRESS)
                and default != argparse.SUPPRESS
                and not isinstance(action, argparse._StoreTrueAction)
                and not isinstance(action, argparse._StoreFalseAction)):
            desc = f"{desc} (default: {default})".strip()
        if action.required:
            desc = f"{desc} (required)".strip()
        rows.append((display, desc or "-"))
    return rows


def _table(headers: list[str], rows: list[tuple[str, str]]) -> str:
    lines = ["| " + " | ".join(headers) + " |",
             "|" + "|".join(["---"] * len(headers)) + "|"]
    lines += [f"| {c0} | {c1} |" for c0, c1 in rows]
    return "\n".join(lines) + "\n"


def _command_markdown(cmd: str, sub_action: argparse._SubParsersAction) -> str:
    parser = sub_action.choices[cmd]
    desc = _choice_help(sub_action, cmd)
    parts = [GENERATED_NOTE, "", f"# `candid {cmd}`", ""]
    if desc:
        parts += [desc, ""]
    parts += ["## Usage", "", "```", _usage(parser), "```", ""]

    nested = _subparsers_action(parser)
    if nested:
        rows = [(f"`{name}`", _choice_help(nested, name) or "-")
                for name in nested.choices]
        parts += ["## Subcommands", "", _table(["Subcommand", "Description"], rows), ""]
        for name, sub in nested.choices.items():
            sub_help = _choice_help(nested, name)
            parts += [f"### `candid {cmd} {name}`", ""]
            if sub_help:
                parts += [sub_help, ""]
            parts += ["```", _usage(sub), "```", ""]
            opt_rows = _option_rows(sub)
            if opt_rows:
                parts += [_table(["Option", "Description"], opt_rows), ""]
    else:
        opt_rows = _option_rows(parser)
        if opt_rows:
            parts += ["## Options", "", _table(["Option", "Description"], opt_rows), ""]
    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = build_parser()
    sub_action = _subparsers_action(parser)
    missing = [c for c in COMMANDS if c not in sub_action.choices]
    if missing:
        print(f"ERROR: commands missing from parser: {missing}", file=sys.stderr)
        return 1
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    written, unchanged = 0, 0
    for cmd in COMMANDS:
        text = _command_markdown(cmd, sub_action)
        path = OUT_DIR / f"{cmd}.md"
        if path.is_file() and path.read_text(encoding="utf-8") == text:
            unchanged += 1
            continue
        path.write_text(text, encoding="utf-8")
        written += 1
    # drop stale pages for commands that no longer exist
    for stale in OUT_DIR.glob("*.md"):
        if stale.stem not in COMMANDS:
            stale.unlink()
            print(f"removed stale page: {stale.name}")
    print(f"commands docs: {written} written, {unchanged} unchanged -> {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
