"""Shell completion scripts for the candid CLI, generated from the live parser.

Single source of truth: the scripts are produced by walking the parser
built by ``candid.__main__.build_parser()`` (imported lazily at call time,
so ``__main__`` can import this module without a cycle) and emitting the
command + subcommand + option word lists for bash, zsh and fish.

Usage (once wired into the CLI)::

    python -m candid completions bash|zsh|fish
"""

from __future__ import annotations

import argparse

SHELLS = ("bash", "zsh", "fish")

#: Options that take a file path - these get file completion in the scripts.
_FILE_OPTS = {
    "--jd", "--resume", "--linkedin", "--out", "--file", "--zip",
    "--dest", "--text", "--gmail-takeout", "--linkedin-zip",
}


# ---------------------------------------------------------------------------
# parser walking (single source of truth)
# ---------------------------------------------------------------------------

def _subparsers_action(parser):
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _choice_help(subparsers_action):
    """Map subcommand name -> help text (argparse stashes it in pseudo-actions)."""
    out = {}
    for pseudo in getattr(subparsers_action, "_choices_actions", []):
        if pseudo.help:
            out[pseudo.dest] = pseudo.help
    return out


def _takes_value(action) -> bool:
    return not isinstance(
        action,
        (argparse._StoreTrueAction, argparse._StoreFalseAction,
         argparse._CountAction, argparse._HelpAction, argparse._VersionAction),
    )


def _options_of(parser):
    """[(option_strings, help, takes_value)] for a (sub)parser."""
    opts = []
    for action in parser._actions:
        if not action.option_strings:
            continue
        opts.append((list(action.option_strings), action.help or "",
                     _takes_value(action)))
    return opts


def _sub_info(sub):
    """{"subs": [(name, help)], "sub_opts": {name: [options]}} for one command."""
    info = {"subs": [], "sub_opts": {}}
    nsp = _subparsers_action(sub)
    if nsp is not None:
        helps = _choice_help(nsp)
        seen = set()
        for name, ssub in nsp.choices.items():
            if id(ssub) in seen:  # alias pointing at the same parser
                continue
            seen.add(id(ssub))
            info["subs"].append((name, helps.get(name, "")))
            info["sub_opts"][name] = _options_of(ssub)
    else:
        # positional with choices, e.g. `profile [show]`
        for action in sub._actions:
            choices = getattr(action, "choices", None)
            if action.option_strings or not choices:
                continue
            for choice in choices:
                info["subs"].append((str(choice), ""))
    return info


def command_tree(parser):
    """Walk a live argparse parser.

    Returns ``(tree, top_opts)`` where ``tree`` maps a command name to
    ``{"help": str, "opts": [...], "subs": [(name, help)],
    "sub_opts": {name: [...]}}`` and ``top_opts`` are the top parser's own
    options (e.g. ``--version``).
    """
    tree = {}
    sp = _subparsers_action(parser)
    helps = _choice_help(sp) if sp is not None else {}
    seen = set()
    if sp is not None:
        for name, sub in sp.choices.items():
            if id(sub) in seen:  # alias
                continue
            seen.add(id(sub))
            tree[name] = {"help": helps.get(name, ""),
                          "opts": _options_of(sub),
                          **_sub_info(sub)}
    return tree, _options_of(parser)


def _one_line(text: str) -> str:
    return " ".join(text.split())


# ---------------------------------------------------------------------------
# bash
# ---------------------------------------------------------------------------

def _bash_var(name: str) -> str:
    return name.replace("-", "_")


def generate_bash(parser) -> str:
    """Bash completion: ``complete -F`` function, subcommand-aware, no deps."""
    tree, top_opts = command_tree(parser)
    top_longs = " ".join(o for opts, _, _ in top_opts for o in opts
                         if o.startswith("--"))

    lines = [
        "# bash completion for candid.",
        "# Generated by `python -m candid completions bash` - do not edit by hand.",
        "#",
        "# Install (pick one):",
        '#   eval "$(python -m candid completions bash)"',
        "#   python -m candid completions bash >> ~/.bash_completion  # then restart your shell",
        "#",
        "# Completes `candid ...` and `python -m candid ...` / `python3 -m candid ...`.",
        "# Generated from the live CLI parser, so it always matches this candid.",
        "",
        f'_candid_cmds="{" ".join(tree)}"',
        f'_candid_top_opts="{top_longs}"',
    ]
    value_opts = set()
    for name, info in tree.items():
        key = _bash_var(name)
        longs = " ".join(o for opts, _, _ in info["opts"] for o in opts)
        lines.append(f'_candid_opts_{key}="{longs}"')
        subs = " ".join(n for n, _ in info["subs"])
        lines.append(f'_candid_subs_{key}="{subs}"')
        for sname, sopts in info["sub_opts"].items():
            slongs = " ".join(o for opts, _, _ in sopts for o in opts)
            lines.append(f'_candid_subopts_{key}_{_bash_var(sname)}="{slongs}"')
        for opts, _, takes in info["opts"]:
            if takes:
                value_opts.update(o for o in opts if o.startswith("--"))
        for sopts in info["sub_opts"].values():
            for opts, _, takes in sopts:
                if takes:
                    value_opts.update(o for o in opts if o.startswith("--"))
    # drop --help: completing its "value" should fall back to defaults too
    value_opts.add("--help")
    value_alternation = "|".join(sorted(value_opts))

    lines += [
        "",
        "_candid_complete() {",
        "    local cur prev cmd sub",
        "    COMPREPLY=()",
        '    cur="${COMP_WORDS[COMP_CWORD]}"',
        '    prev="${COMP_WORDS[COMP_CWORD-1]:-}"',
        "",
        "    # program prefix: `candid` (skip 1 word) or `python -m candid` (skip 3)",
        "    local skip=1",
        '    case "${COMP_WORDS[0]}" in',
        "        candid) ;;",
        "        python*)",
        '            if [[ "${COMP_WORDS[1]}" == "-m" && "${COMP_WORDS[2]}" == "candid" ]]; then',
        "                skip=3",
        "            else",
        "                return 1",
        "            fi",
        "            ;;",
        "        *) return 1 ;;",
        "    esac",
        "",
        "    # After an option that takes a value, fall back to default completion.",
        '    case "$prev" in',
        f"        {value_alternation}) return 0 ;;",
        "    esac",
        "",
        "    # positional words (options skipped)",
        "    local -a pos=()",
        "    local i w",
        "    for ((i=skip; i<COMP_CWORD; i++)); do",
        '        w="${COMP_WORDS[i]}"',
        '        [[ "$w" == -* ]] && continue',
        '        pos+=("$w")',
        "    done",
        "",
        '    local words=""',
        "    if ((${#pos[@]} == 0)); then",
        '        words="$_candid_cmds $_candid_top_opts"',
        "    elif ((${#pos[@]} == 1)); then",
        '        cmd="${pos[0]//-/_}"',
        '        local vsub="_candid_subs_$cmd" vopt="_candid_opts_$cmd"',
        '        words="${!vsub:-} ${!vopt:-}"',
        "    else",
        '        cmd="${pos[0]//-/_}"',
        '        sub="${pos[1]//-/_}"',
        '        local vsub="_candid_subopts_${cmd}_${sub}" vopt="_candid_opts_$cmd"',
        '        if [[ -n "${!vsub:-}" ]]; then',
        '            words="${!vsub}"',
        "        else",
        '            words="${!vopt:-}"',
        "        fi",
        "    fi",
        "",
        '    COMPREPLY=($(compgen -W "$words" -- "$cur"))',
        "    return 0",
        "}",
        "",
        "complete -F _candid_complete -o default candid",
        "complete -F _candid_complete -o default python",
        "complete -F _candid_complete -o default python3",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# zsh
# ---------------------------------------------------------------------------

def _zsh_escape(text: str) -> str:
    return (text.replace("\\", "\\\\")
                .replace("'", "'\\''")
                .replace("[", "\\[").replace("]", "\\]")
                .replace(":", "\\:"))


def _zsh_opt_spec(opt_strings, help_text: str, takes_value: bool) -> str:
    desc = _zsh_escape(_one_line(help_text))
    joined = " ".join(opt_strings)
    if not takes_value:
        return f"{joined}[{desc}]"
    if any(o in _FILE_OPTS for o in opt_strings):
        return f"{joined}[{desc}]:file:_files"
    return f"{joined}[{desc}]: :"


def generate_zsh(parser) -> str:
    """Zsh completion using the canonical _arguments state machine."""
    tree, _ = command_tree(parser)
    lines = [
        "#compdef candid",
        "# zsh completion for candid.",
        "# Generated by `python -m candid completions zsh` - do not edit by hand.",
        "#",
        "# Install:",
        "#   mkdir -p ~/.zsh/completions",
        "#   python -m candid completions zsh > ~/.zsh/completions/_candid",
        "#   # then in ~/.zshrc (before compinit):",
        "#   fpath=(~/.zsh/completions $fpath)",
        "#",
        "# Tip: `alias candid='python -m candid'` makes this fire for that form too.",
        "",
        "_candid() {",
        "    local context state line",
        "    typeset -A opt_args",
        "",
        "    _arguments -C \\",
        "        '1:command:->cmd' \\",
        "        '*:: :->args' && return 0",
        "",
        "    case $state in",
        "        cmd)",
        "            local -a _cmds",
        "            _cmds=(",
    ]
    for name, info in tree.items():
        lines.append(f"                '{name}:{_zsh_escape(_one_line(info['help']))}'")
    lines += [
        "            )",
        "            _describe -t commands 'candid command' _cmds",
        "            ;;",
        "        args)",
        "            case $line[1] in",
    ]
    for name, info in tree.items():
        lines.append(f"                {name})")
        specs = [_zsh_opt_spec(o, h, t) for o, h, t in info["opts"]]
        if info["subs"]:
            lines += [
                "                    if (( CURRENT == 3 )); then",
                "                        local -a _subs",
                "                        _subs=(",
            ]
            for sname, shelp in info["subs"]:
                lines.append(f"                            '{sname}:{_zsh_escape(_one_line(shelp))}'")
            lines += [
                "                        )",
                f"                        _describe -t subcommands '{name} subcommand' _subs",
                "                    else",
            ]
            if any(info["sub_opts"].values()):
                lines.append("                        case $words[3] in")
                for sname, sopts in info["sub_opts"].items():
                    lines.append(f"                            {sname})")
                    sspecs = [_zsh_opt_spec(o, h, t) for o, h, t in sopts]
                    if sspecs:
                        lines.append("                                _arguments \\")
                        for i, spec in enumerate(sspecs):
                            cont = " \\" if i < len(sspecs) - 1 else ""
                            lines.append(f"                                    '{spec}'{cont}")
                    lines.append("                                ;;")
                lines.append("                            *)")
                if specs:
                    lines.append("                                _arguments \\")
                    for i, spec in enumerate(specs):
                        cont = " \\" if i < len(specs) - 1 else ""
                        lines.append(f"                                    '{spec}'{cont}")
                lines.append("                                ;;")
                lines.append("                        esac")
            elif specs:
                lines.append("                        _arguments \\")
                for i, spec in enumerate(specs):
                    cont = " \\" if i < len(specs) - 1 else ""
                    lines.append(f"                                    '{spec}'{cont}")
            lines.append("                    fi")
            lines.append("                    ;;")
        elif specs:
            lines.append("                    _arguments \\")
            for i, spec in enumerate(specs):
                cont = " \\" if i < len(specs) - 1 else ""
                lines.append(f"                    '{spec}'{cont}")
            lines.append("                    ;;")
        else:
            lines.append("                    ;;")
    lines += [
        "            esac",
        "            ;;",
        "    esac",
        "}",
        "",
        '_candid "$@"',
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# fish
# ---------------------------------------------------------------------------

def _fish_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("'", "\\'")


def generate_fish(parser) -> str:
    """Fish completion: condition-guarded, dependency-free."""
    tree, _ = command_tree(parser)
    lines = [
        "# fish completion for candid.",
        "# Generated by `python -m candid completions fish` - do not edit by hand.",
        "#",
        "# Install:",
        "#   mkdir -p ~/.config/fish/completions",
        "#   python -m candid completions fish > ~/.config/fish/completions/candid.fish",
        "#",
        "# Covers `candid ...` and `python -m candid ...` (via the python/python3 entries).",
        "# Generated from the live CLI parser, so it always matches this candid.",
        "",
        "function __candid_active",
        "    set -l toks (commandline -opc)",
        "    if test (count $toks) -ge 1; and test $toks[1] = candid",
        "        return 0",
        "    end",
        "    if test (count $toks) -ge 3; and string match -q -- 'python*' $toks[1]; and test $toks[2] = -m; and test $toks[3] = candid",
        "        return 0",
        "    end",
        "    return 1",
        "end",
        "",
        "function __candid_rest",
        "    # tokens after the program prefix (`candid` or `python -m candid`)",
        "    set -l toks (commandline -opc)",
        "    set -e toks[1]",
        "    if test (count $toks) -ge 2; and test $toks[1] = -m; and test $toks[2] = candid",
        "        set -e toks[1..2]",
        "    end",
        "    printf '%s\\n' $toks",
        "end",
        "",
        "function __candid_first",
        "    # first non-option token, i.e. the top-level command",
        "    for t in (__candid_rest)",
        "        string match -q -- '-*' $t; and continue",
        "        echo $t",
        "        return 0",
        "    end",
        "    return 1",
        "end",
        "",
        "function __candid_needs_command",
        "    __candid_active; or return 1",
        "    not __candid_first >/dev/null",
        "end",
        "",
        "function __candid_cmd_is",
        "    # __candid_cmd_is <cmd>... : completing args of one of these commands",
        "    __candid_active; or return 1",
        "    set -l first (__candid_first)",
        "    test -n \"$first\"; and contains -- $first $argv",
        "end",
        "",
        "function __candid_cmd_needs_sub",
        "    # __candid_cmd_needs_sub <cmd>... : completing the subcommand slot",
        "    __candid_cmd_is $argv; or return 1",
        "    set -l n 0",
        "    for t in (__candid_rest)",
        "        string match -q -- '-*' $t; and continue",
        "        set n (math $n + 1)",
        "    end",
        "    test $n -eq 1",
        "end",
        "",
        "function __candid_sub_is",
        "    # __candid_sub_is <cmd> <sub> : completing args after that subcommand",
        "    __candid_cmd_is $argv[1]; or return 1",
        "    set -l words",
        "    for t in (__candid_rest)",
        "        string match -q -- '-*' $t; and continue",
        "        set -a words $t",
        "    end",
        "    test (count $words) -ge 2; and test $words[2] = $argv[2]",
        "end",
        "",
    ]
    for name, info in tree.items():
        desc = _fish_escape(_one_line(info["help"]))
        lines.append(f"# --- {name} ---")
        for prog in ("candid", "python", "python3"):
            lines.append(
                f"complete -c {prog} -f -n __candid_needs_command "
                f"-a '{name}' -d '{desc}'")
        for opt_strings, help_text, takes in info["opts"]:
            flags = []
            for o in opt_strings:
                if o.startswith("--"):
                    flags.append(f"-l {o[2:]}")
                elif len(o) == 2 and o.startswith("-"):
                    flags.append(f"-s {o[1]}")
            if not flags:
                continue
            odesc = _fish_escape(_one_line(help_text))
            extra = " -r" if takes else ""
            # -f (no file completion) unless this option takes a file path
            if takes and not any(o in _FILE_OPTS for o in opt_strings):
                extra += " -f"
            lines.append(
                f"complete -c candid -n '__candid_cmd_is {name}' "
                f"{' '.join(flags)} -d '{odesc}'{extra}")
        for sname, shelp in info["subs"]:
            sdesc = _fish_escape(_one_line(shelp))
            for prog in ("candid", "python", "python3"):
                lines.append(
                    f"complete -c {prog} -f -n '__candid_cmd_needs_sub {name}' "
                    f"-a '{sname}' -d '{sdesc}'")
        for sname, sopts in info["sub_opts"].items():
            for opt_strings, help_text, takes in sopts:
                flags = []
                for o in opt_strings:
                    if o.startswith("--"):
                        flags.append(f"-l {o[2:]}")
                    elif len(o) == 2 and o.startswith("-"):
                        flags.append(f"-s {o[1]}")
                if not flags:
                    continue
                odesc = _fish_escape(_one_line(help_text))
                extra = " -r" if takes else ""
                if takes and not any(o in _FILE_OPTS for o in opt_strings):
                    extra += " -f"
                lines.append(
                    f"complete -c candid -n '__candid_sub_is {name} {sname}' "
                    f"{' '.join(flags)} -d '{odesc}'{extra}")
        lines.append("")
    return "\n".join(lines)


_GENERATORS = {
    "bash": generate_bash,
    "zsh": generate_zsh,
    "fish": generate_fish,
}


# ---------------------------------------------------------------------------
# CLI wiring
# ---------------------------------------------------------------------------

def cmd_completions(args) -> None:
    """Print the completion script for the requested shell to stdout."""
    # Lazy import: this module is imported by candid.__main__ at CLI build
    # time, so importing build_parser at module level would be a cycle.
    from candid.__main__ import build_parser
    parser = build_parser()
    print(_GENERATORS[args.shell](parser))


def register(subparsers) -> None:
    """Add the `completions` command to the CLI parser."""
    s = subparsers.add_parser(
        "completions",
        help="Print a shell completion script (bash/zsh/fish) generated "
             "from the live CLI parser.",
        description="Print a shell completion script generated from the live "
                    "CLI parser, so completions always match this candid. "
                    "The command itself is included, so re-run after upgrades.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="examples:\n"
               '  eval "$(python -m candid completions bash)"\n'
               "  python -m candid completions zsh > ~/.zsh/completions/_candid\n"
               "  python -m candid completions fish > ~/.config/fish/completions/candid.fish",
    )
    s.add_argument("shell", choices=list(SHELLS),
                   help="Shell to generate a completion script for")
    s.set_defaults(func=cmd_completions)
