"""Prior-work map and rebuttal trainer for research-oriented users.

FEATURE 1 - prior-work map
    Organize the user's research projects and publications into a
    timeline map. Input entries look like::

        {
          "title": str,          # required
          "year": int,           # optional; undated entries are kept last
          "kind": "project" | "publication",   # default "project"
          "areas": [str, ...],   # topic tags, e.g. ["nlp", "evaluation"]
          "claims": [str, ...],  # user-stated contribution claims
          "techniques": [str, ...],
        }

    build_map(entries) builds a map dict with a chronological timeline,
    area coverage, technique frequency, a claims index, and heuristic
    gap observations. render_map / render_map_md render it as text or
    Markdown. Projects can also come from the candid profile's optional
    "projects" list (load_entries falls back cleanly when it is absent).

FEATURE 2 - rebuttal trainer
    The user pastes reviewer-style critiques they received (never
    generated by candid). Each critique is classified by keyword
    heuristics, gets a response template for its type, and the user can
    draft a response and mark it addressed or pending. Critiques and
    drafts persist as JSON at candid_data/rebuttals.json (git-ignored).

Everything is local and offline: no network, no APIs, no scraping.
Nothing here invents experience, metrics, or publications. All maps
derive strictly from user-supplied entries, and every gap observation
is labeled as a heuristic suggestion, not a fact.
"""

from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path

from candid import config as C

# Path constant lives in this module (not config.py) per the batch-97
# ownership rules. It still follows the config.py convention: user data
# under DATA_DIR, overridable via CANDID_DATA_DIR.
REBUTTAL_PATH = C.DATA_DIR / "rebuttals.json"


class ResearchMapError(Exception):
    """Raised for invalid entries, critiques, or stored data."""


# ---------------------------------------------------------------------------
# feature 1: prior-work map
# ---------------------------------------------------------------------------

ENTRY_KINDS = ("project", "publication")

_RECENCY_WINDOW = 2  # years; "last 2 years" means this year + last year


def _str_list(value, field: str, idx: int) -> list[str]:
    """Normalize an entry list field: strings stay strings, deduped."""
    if value is None:
        return []
    if isinstance(value, str):
        value = [value]
    if not isinstance(value, list):
        raise ResearchMapError(
            f"Entry #{idx}: '{field}' must be a list of strings."
        )
    seen: set[str] = set()
    out: list[str] = []
    for item in value:
        s = str(item).strip()
        if s and s.lower() not in seen:
            seen.add(s.lower())
            out.append(s)
    return out


def _normalize_entry(raw: dict, idx: int) -> dict:
    """Validate one user-supplied entry and normalize it to the map schema."""
    if not isinstance(raw, dict):
        raise ResearchMapError(
            f"Entry #{idx} must be an object, got {type(raw).__name__}."
        )
    title = str(raw.get("title") or "").strip()
    if not title:
        raise ResearchMapError(f"Entry #{idx} is missing a title.")
    year = raw.get("year")
    if year is not None and year != "":
        try:
            year = int(year)
        except (TypeError, ValueError) as exc:
            raise ResearchMapError(
                f"Entry '{title}': year {year!r} is not a valid year."
            ) from exc
    else:
        year = None
    kind = str(raw.get("kind") or "project").strip().lower()
    if kind not in ENTRY_KINDS:
        raise ResearchMapError(
            f"Entry '{title}': kind must be one of "
            f"{', '.join(ENTRY_KINDS)}, got {kind!r}."
        )
    return {
        "title": title,
        "year": year,
        "kind": kind,
        "areas": _str_list(raw.get("areas"), "areas", idx),
        "claims": _str_list(raw.get("claims"), "claims", idx),
        "techniques": _str_list(raw.get("techniques"), "techniques", idx),
    }


# keyword heuristics for classifying user-stated claims (method vs
# empirical). Used only to notice a lopsided mix; the result is surfaced
# as a suggestion, never a fact.
_EMPIRICAL_CLAIM_RES = [
    r"\baccuracy\b", r"\bf1\b", r"\boutperform", r"\bimprov\w*\b",
    r"\bbenchmark", r"\bevaluat\w*\b", r"\bexperiment\w*\b",
    r"\bstate-of-the-art\b", r"\bsota\b", r"\bgain\w*\b",
    r"\breduc\w+\b", r"%\b",
]
_METHOD_CLAIM_RES = [
    r"\bnovel\b", r"\bpropos\w*\b", r"\bframework\b",
    r"\barchitecture\b", r"\balgorithm\b", r"\bdesign\w*\b",
    r"\bmethod\b", r"\bapproach\b", r"\bintroduc\w*\b",
]


def _claim_kind(claim: str) -> str:
    """Heuristically tag a user-stated claim as empirical, method, or other."""
    low = claim.lower()
    if any(re.search(p, low) for p in _EMPIRICAL_CLAIM_RES):
        return "empirical"
    if any(re.search(p, low) for p in _METHOD_CLAIM_RES):
        return "method"
    return "other"


def _suggest_label(suggestion: str) -> str:
    """Prefix every gap suggestion so it reads as a suggestion, not a fact."""
    return f"Suggestion (heuristic, not a fact): {suggestion}"


def build_map(entries: list[dict]) -> dict:
    """Build a prior-work map from user-supplied project/publication entries.

    Returns a dict with: entry_count, project/publication counts,
    timeline (chronological, undated entries last), years summary,
    area_coverage, technique_frequency, claims_index, claim_kinds, and
    gaps (see gap_observations).
    """
    normed = [_normalize_entry(e, i) for i, e in enumerate(entries or [])]

    dated = [e for e in normed if e["year"] is not None]
    undated = [e for e in normed if e["year"] is None]
    timeline = sorted(dated, key=lambda e: (e["year"], e["title"].lower()))
    timeline.extend(sorted(undated, key=lambda e: e["title"].lower()))

    by_year: dict[int, int] = {}
    for e in dated:
        by_year[e["year"]] = by_year.get(e["year"], 0) + 1

    area_coverage: dict[str, int] = {}
    for e in normed:
        for a in e["areas"]:
            area_coverage[a] = area_coverage.get(a, 0) + 1

    technique_frequency: dict[str, int] = {}
    for e in normed:
        for t in e["techniques"]:
            technique_frequency[t] = technique_frequency.get(t, 0) + 1

    claims_index: list[dict] = []
    claim_kinds = {"empirical": 0, "method": 0, "other": 0}
    for e in normed:
        for claim in e["claims"]:
            kind = _claim_kind(claim)
            claim_kinds[kind] += 1
            claims_index.append({
                "claim": claim,
                "claim_kind": kind,
                "entry": e["title"],
                "year": e["year"],
            })

    map_: dict = {
        "entry_count": len(normed),
        "projects": sum(1 for e in normed if e["kind"] == "project"),
        "publications": sum(1 for e in normed if e["kind"] == "publication"),
        "timeline": timeline,
        "years": {
            "start": min(by_year) if by_year else None,
            "end": max(by_year) if by_year else None,
            "by_year": by_year,
            "undated": len(undated),
        },
        "area_coverage": dict(
            sorted(area_coverage.items(), key=lambda kv: (-kv[1], kv[0].lower()))
        ),
        "technique_frequency": dict(
            sorted(technique_frequency.items(), key=lambda kv: (-kv[1], kv[0].lower()))
        ),
        "claims_index": claims_index,
        "claim_kinds": claim_kinds,
    }
    map_["gaps"] = gap_observations(map_)
    return map_


def gap_observations(map_: dict) -> list[dict]:
    """Heuristic gap observations over a prior-work map.

    Returns a list of {"observation", "suggestion"} dicts. Every
    suggestion is explicitly labeled as a heuristic, never a fact, and
    nothing is invented: observations only describe what the supplied
    entries do (or do not) contain.
    """
    gaps: list[dict] = []
    total = map_.get("entry_count", 0)
    timeline: list[dict] = map_.get("timeline", [])
    if total == 0:
        gaps.append({
            "observation": "The map has no entries yet.",
            "suggestion": _suggest_label(
                "Add your projects and publications (title, year, kind, "
                "areas, claims, techniques) so the map has something to organize."
            ),
        })
        return gaps

    current = date.today().year
    recent_years = {current, current - 1}

    # areas that appear only in older entries (nothing in the last 2 years)
    area_latest: dict[str, int] = {}
    for e in timeline:
        if e.get("year") is None:
            continue
        for a in e.get("areas", []):
            area_latest[a] = max(area_latest.get(a, 0), e["year"])
    for area in sorted(area_latest):
        if area_latest[area] < current - (_RECENCY_WINDOW - 1):
            gaps.append({
                "observation": (
                    f"No entries tagged '{area}' in the last "
                    f"{_RECENCY_WINDOW} years."
                ),
                "suggestion": _suggest_label(
                    f"If you are still active in {area}, add recent entries "
                    f"tagged with it; if not, the gap may simply reflect a "
                    f"shift in focus."
                ),
            })

    # claim mix: method-only vs empirical
    kinds = map_.get("claim_kinds", {})
    n_claims = len(map_.get("claims_index", []))
    if n_claims == 0:
        gaps.append({
            "observation": "No contribution claims are stated on any entry.",
            "suggestion": _suggest_label(
                "Consider writing down what you actually contributed on each "
                "entry (a method you designed, a result you measured). "
                "Only state claims that are true; never invent metrics."
            ),
        })
    elif kinds.get("empirical", 0) == 0 and kinds.get("method", 0) > 0:
        gaps.append({
            "observation": (
                "All claims are method claims; none are empirical."
            ),
            "suggestion": _suggest_label(
                "If any of your entries have measured results you can state, "
                "adding them would balance the story. Do not invent numbers; "
                "state only results you actually have."
            ),
        })

    # kind balance
    if map_.get("publications", 0) == 0:
        gaps.append({
            "observation": "No publications recorded; all entries are projects.",
            "suggestion": _suggest_label(
                "If any of this work was published, add publication entries. "
                "Otherwise the map may simply reflect unpublished work."
            ),
        })

    # undated entries
    undated = map_.get("years", {}).get("undated", 0)
    if undated:
        gaps.append({
            "observation": f"{undated} entr{'y' if undated == 1 else 'ies'} "
                           f"have no year and sit outside the timeline.",
            "suggestion": _suggest_label(
                "Fill in years where you know them so the timeline reflects "
                "the real chronology."
            ),
        })

    # technique concentration
    tech_freq: dict[str, int] = map_.get("technique_frequency", {})
    if total >= 3 and tech_freq:
        top_tech, top_n = max(tech_freq.items(), key=lambda kv: kv[1])
        if top_n / total > 0.6:
            gaps.append({
                "observation": (
                    f"'{top_tech}' appears in {top_n} of {total} entries."
                ),
                "suggestion": _suggest_label(
                    f"Heavy concentration on {top_tech} is fine if it is "
                    f"your specialty, but make sure the map also shows the "
                    f"breadth you actually have."
                ),
            })

    return gaps


def render_map(map_: dict) -> str:
    """Render a prior-work map as plain text."""
    lines = [
        f"Prior-work map: {map_.get('entry_count', 0)} entries "
        f"({map_.get('projects', 0)} projects, {map_.get('publications', 0)} publications)",
        "",
        "Timeline (chronological):",
    ]
    for e in map_.get("timeline", []):
        year = e.get("year") if e.get("year") is not None else "undated"
        areas = f" [{', '.join(e['areas'])}]" if e.get("areas") else ""
        lines.append(f"  {year}: {e['title']} ({e['kind']}){areas}")

    lines += ["", "Area coverage:"]
    coverage: dict[str, int] = map_.get("area_coverage", {})
    if coverage:
        for area, n in coverage.items():
            lines.append(f"  {area}: {n} entr{'y' if n == 1 else 'ies'}")
    else:
        lines.append("  (no areas tagged)")

    lines += ["", "Technique frequency:"]
    techs: dict[str, int] = map_.get("technique_frequency", {})
    if techs:
        for tech, n in techs.items():
            lines.append(f"  {tech}: {n}")
    else:
        lines.append("  (no techniques listed)")

    lines += ["", "Claims index:"]
    claims: list[dict] = map_.get("claims_index", [])
    if claims:
        for c in claims:
            year = f" ({c['year']})" if c.get("year") is not None else ""
            lines.append(f"  [{c['claim_kind']}] \"{c['claim']}\" - {c['entry']}{year}")
    else:
        lines.append("  (no claims stated)")

    lines += ["", "Gap observations (heuristic suggestions, not facts):"]
    gaps: list[dict] = map_.get("gaps", [])
    if gaps:
        for g in gaps:
            lines.append(f"  - {g['observation']}")
            lines.append(f"    {g['suggestion']}")
    else:
        lines.append("  (none)")
    return "\n".join(lines)


def render_map_md(map_: dict) -> str:
    """Render a prior-work map as Markdown."""
    lines = [
        "# Prior-work map",
        "",
        f"**{map_.get('entry_count', 0)} entries** "
        f"({map_.get('projects', 0)} projects, "
        f"{map_.get('publications', 0)} publications)",
        "",
        "## Timeline",
        "",
        "| Year | Title | Kind | Areas |",
        "| --- | --- | --- | --- |",
    ]
    for e in map_.get("timeline", []):
        year = str(e.get("year")) if e.get("year") is not None else "undated"
        areas = ", ".join(e.get("areas", []))
        lines.append(f"| {year} | {e['title']} | {e['kind']} | {areas} |")

    lines += ["", "## Area coverage", ""]
    coverage: dict[str, int] = map_.get("area_coverage", {})
    if coverage:
        lines += ["| Area | Entries |", "| --- | --- |"]
        for area, n in coverage.items():
            lines.append(f"| {area} | {n} |")
    else:
        lines.append("_No areas tagged._")

    lines += ["", "## Technique frequency", ""]
    techs: dict[str, int] = map_.get("technique_frequency", {})
    if techs:
        lines += ["| Technique | Entries |", "| --- | --- |"]
        for tech, n in techs.items():
            lines.append(f"| {tech} | {n} |")
    else:
        lines.append("_No techniques listed._")

    lines += ["", "## Claims index", ""]
    claims: list[dict] = map_.get("claims_index", [])
    if claims:
        for c in claims:
            year = f" ({c['year']})" if c.get("year") is not None else ""
            lines.append(
                f"- **[{c['claim_kind']}]** \"{c['claim']}\" "
                f"- *{c['entry']}*{year}"
            )
    else:
        lines.append("_No claims stated._")

    lines += ["", "## Gap observations", "",
              "_Heuristic suggestions, not facts._", ""]
    gaps: list[dict] = map_.get("gaps", [])
    if gaps:
        for g in gaps:
            lines.append(f"- **{g['observation']}**")
            lines.append(f"  - {g['suggestion']}")
    else:
        lines.append("_None._")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# loading entries: profile projects, JSON, or a plain list
# ---------------------------------------------------------------------------

def load_profile_projects(profile_path: str | Path | None = None) -> list[dict]:
    """Load projects from the candid profile's optional "projects" list.

    The profile schema does not guarantee a "projects" key, so this is
    best-effort: returns [] when the profile is missing, unreadable, or
    has no projects. Never raises for a missing profile.
    """
    p = Path(profile_path) if profile_path else C.PROFILE_PATH
    if not p.exists():
        return []
    try:
        profile = json.loads(p.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return []
    projects = (profile or {}).get("projects") or []
    return projects if isinstance(projects, list) else []


def load_entries(source: list[dict] | str | Path | None = None, *,
                 profile_path: str | Path | None = None) -> list[dict]:
    """Load raw entries from a JSON file, a list of dicts, or the profile.

    - list -> returned as-is (validated later by build_map).
    - str/Path -> JSON file: either a bare list or {"entries": [...]}.
    - None -> the candid profile's "projects" list, if present; clean
      fallback to [] when the profile has none (no exception).
    """
    if isinstance(source, list):
        return source
    if isinstance(source, (str, Path)):
        p = Path(source)
        if not p.exists():
            raise ResearchMapError(f"Entries file not found: {p}")
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ResearchMapError(
                f"Entries file {p} is not valid JSON: {exc}"
            ) from exc
        raw = data.get("entries") if isinstance(data, dict) else data
        if not isinstance(raw, list):
            raise ResearchMapError(
                f"Entries file {p} should contain a JSON list "
                f"(or an object with an 'entries' list)."
            )
        return raw
    return load_profile_projects(profile_path)


# ---------------------------------------------------------------------------
# feature 2: rebuttal trainer
# ---------------------------------------------------------------------------

# critique type -> keyword heuristics (matched case-insensitively against
# the critique text). Order is the classification priority.
_CRITIQUE_KEYWORDS: dict[str, list[str]] = {
    "clarity": ["unclear", "confus", "clarif", "poorly written",
                "hard to follow", "typo", "notation", "vague",
                "rewrite", "proofread"],
    "experiments": ["experiment", "ablation", "evaluation", "dataset",
                    "empirical", "results", "analysis"],
    "baselines": ["baseline", "compar", "state-of-the-art", "sota"],
    "novelty": ["novel", "incremental", "prior work", "existing work",
                "already", "originality"],
    "significance": ["significan", "impact", "marginal",
                     "limited contribution", "motivat", "why does this matter"],
    "scope": ["scope", "narrow", "generaliz", "only", "setting", "domain"],
}

_CRITIQUE_TYPES = list(_CRITIQUE_KEYWORDS) + ["other"]


def _classify_critique(text: str) -> str:
    """Classify a critique via keyword heuristics (first match wins)."""
    low = (text or "").lower()
    for ctype, keywords in _CRITIQUE_KEYWORDS.items():
        if any(kw in low for kw in keywords):
            return ctype
    return "other"


# Response templates per critique type. Generic structure everywhere:
# acknowledge -> clarify -> evidence or commitment. They deliberately
# contain no claims of data; each reminds the user to cite only results
# they actually have.
_REBUTTAL_TEMPLATES: dict[str, str] = {
    "novelty": (
        "1. Acknowledge: thank the reviewer for engaging with the related "
        "work and restate their concern in your own words, e.g. "
        "[reviewer's specific overlap concern].\n"
        "2. Clarify: state precisely what is new in your work versus the "
        "cited prior work (different problem setting, different method, "
        "different guarantees). Point to the exact section.\n"
        "3. Evidence/commitment: cite the distinguishing experiment or "
        "argument you already have, or commit to a clearer related-work "
        "discussion in the revision. Only cite results you actually have; "
        "never invent a comparison."
    ),
    "experiments": (
        "1. Acknowledge: thank the reviewer for pushing on empirical "
        "rigor and restate what is missing, e.g. [requested experiment or "
        "analysis].\n"
        "2. Clarify: explain what the current experiments do establish, "
        "pointing to the relevant figures/tables.\n"
        "3. Evidence/commitment: either report the requested result if you "
        "already ran it, or commit to running it in the revision with a "
        "concrete plan (what data, what metric, what you expect). Never "
        "fabricate numbers."
    ),
    "clarity": (
        "1. Acknowledge: thank the reviewer for the close read and name "
        "the confusing passage, e.g. [section/figure].\n"
        "2. Clarify: give the intended reading in plain terms, in the "
        "response itself, so the reviewer sees the fix.\n"
        "3. Evidence/commitment: commit to rewriting the passage and/or "
        "adding a clarifying figure or notation table in the revision. "
        "Quote the sentence you will change if you can."
    ),
    "significance": (
        "1. Acknowledge: thank the reviewer for the frank assessment and "
        "restate their concern, e.g. [why they found it marginal].\n"
        "2. Clarify: articulate the problem's importance and who benefits, "
        "grounded in facts already in the paper or your real experience.\n"
        "3. Evidence/commitment: strengthen the motivation section and, if "
        "you have them, add concrete usage evidence. Do not invent impact."
    ),
    "baselines": (
        "1. Acknowledge: agree that strong baselines matter and restate "
        "which comparisons the reviewer wants, e.g. [missing baselines].\n"
        "2. Clarify: explain the baselines you did include and why you "
        "chose them.\n"
        "3. Evidence/commitment: add the requested comparisons if feasible, "
        "or explain precisely why a comparison is infeasible (different "
        "setting, unavailable code) and what you did instead. Never "
        "fabricate numbers; report only real results you have."
    ),
    "scope": (
        "1. Acknowledge: thank the reviewer and restate the scope concern, "
        "e.g. [narrow setting or limited generalization].\n"
        "2. Clarify: state the intended scope of the work and why that "
        "scope is a reasonable, well-defined problem.\n"
        "3. Evidence/commitment: either extend the scope in the revision if "
        "you genuinely can, or explicitly discuss the limitation and when "
        "the method would/would not apply. Do not claim generality you "
        "have not tested."
    ),
    "other": (
        "1. Acknowledge: thank the reviewer and restate their point in "
        "your own words to show you understood it.\n"
        "2. Clarify: address the substance directly, pointing to the "
        "relevant part of the paper.\n"
        "3. Evidence/commitment: say what you will change in the revision "
        "or what evidence you will add. Only promise what you can deliver."
    ),
}


def suggest_template(critique: dict | int, path: str | Path | None = None) -> str:
    """Return the response template for a critique's type.

    Accepts a critique dict (as returned by add_critique) or a critique
    id. The template is a generic acknowledge/clarify/evidence structure
    with placeholders; it invents no content for the user.
    """
    if isinstance(critique, int):
        critique = get_critique(critique, path)
    ctype = (critique or {}).get("type", "other")
    return _REBUTTAL_TEMPLATES.get(ctype, _REBUTTAL_TEMPLATES["other"])


def _load_store(path: str | Path | None = None) -> dict:
    p = Path(path) if path else REBUTTAL_PATH
    if not p.exists():
        return {"critiques": []}
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ResearchMapError(
            f"Rebuttal file {p} is not valid JSON: {exc}"
        ) from exc
    if not isinstance(data, dict) or not isinstance(data.get("critiques"), list):
        raise ResearchMapError(
            f"Rebuttal file {p} should contain an object with a "
            f"'critiques' list."
        )
    return data


def _save_store(store: dict, path: str | Path | None = None) -> Path:
    p = Path(path) if path else REBUTTAL_PATH
    C.ensure_data_dirs()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(store, indent=2), encoding="utf-8")
    return p


def _next_id(store: dict) -> int:
    return max((c.get("id", 0) for c in store["critiques"]), default=0) + 1


def add_critique(text: str, path: str | Path | None = None) -> dict:
    """Add a user-supplied reviewer critique; classify it. Returns the record."""
    t = (text or "").strip()
    if not t:
        raise ResearchMapError("Critique text is empty; nothing to add.")
    store = _load_store(path)
    rec = {
        "id": _next_id(store),
        "text": t,
        "type": _classify_critique(t),
        "status": "pending",
        "draft": "",
        "date_added": date.today().isoformat(),
    }
    store["critiques"].append(rec)
    _save_store(store, path)
    return rec


def get_critique(critique_id: int, path: str | Path | None = None) -> dict:
    """Fetch one critique by id; raise if it does not exist."""
    store = _load_store(path)
    rec = next((c for c in store["critiques"] if c.get("id") == critique_id), None)
    if rec is None:
        raise ResearchMapError(
            f"No critique with id {critique_id}. Use `rebuttal list` to see ids."
        )
    return rec


def list_critiques(status: str | None = None,
                   path: str | Path | None = None) -> list[dict]:
    """List critiques, optionally filtered to 'pending' or 'addressed'."""
    if status is not None and status not in ("pending", "addressed"):
        raise ResearchMapError(
            f"Unknown status '{status}'. Choose 'pending' or 'addressed'."
        )
    critiques = _load_store(path)["critiques"]
    if status:
        critiques = [c for c in critiques if c["status"] == status]
    return sorted(critiques, key=lambda c: c["id"])


def draft_response(critique_id: int, text: str,
                   path: str | Path | None = None) -> dict:
    """Store the user's draft response on a critique. Returns the record.

    Drafting does not change the status; call mark_addressed when the
    response is final.
    """
    store = _load_store(path)
    rec = next((c for c in store["critiques"] if c.get("id") == critique_id), None)
    if rec is None:
        raise ResearchMapError(f"No critique with id {critique_id}.")
    rec["draft"] = (text or "").strip()
    _save_store(store, path)
    return rec


def mark_addressed(critique_id: int, path: str | Path | None = None) -> dict:
    """Mark a critique addressed. Returns the record."""
    store = _load_store(path)
    rec = next((c for c in store["critiques"] if c.get("id") == critique_id), None)
    if rec is None:
        raise ResearchMapError(f"No critique with id {critique_id}.")
    rec["status"] = "addressed"
    _save_store(store, path)
    return rec


def rebuttal_progress(path: str | Path | None = None) -> dict:
    """Progress stats: {"total", "addressed", "pending", "percent_addressed"}."""
    critiques = _load_store(path)["critiques"]
    addressed = sum(1 for c in critiques if c.get("status") == "addressed")
    total = len(critiques)
    return {
        "total": total,
        "addressed": addressed,
        "pending": total - addressed,
        "percent_addressed": round(100.0 * addressed / total, 1) if total else 0.0,
    }
