"""Interactive STRIDE threat-modeling practice drills.

STRIDE is the classic threat-classification mnemonic: for each letter the
candidate must brainstorm concrete threats against a scenario's assets. This
module provides a small library of realistic scenarios with per-letter hint
threats, a scorer that grades a candidate's answer by keyword overlap against
the hints, and an interactive drill loop used in security-engineer interview
prep.
"""

from __future__ import annotations

import re

STRIDE: dict[str, str] = {
    "S": "Spoofing",
    "T": "Tampering",
    "R": "Repudiation",
    "I": "Information disclosure",
    "D": "Denial of service",
    "E": "Elevation of privilege",
}

SCENARIOS: list[dict] = [
    {
        "id": "file-upload-service",
        "title": "File-upload service",
        "description": (
            "Users upload profile pictures and documents through a web UI. "
            "Files land in object storage, thumbnails are generated by a "
            "worker, and downloads are served through a CDN with signed "
            "URLs. The upload endpoint validates MIME types on the client "
            "and enforces a 25 MB size limit."
        ),
        "assets": [
            "Uploaded files and object storage buckets",
            "Thumbnail generation worker",
            "Signed CDN download URLs",
            "User session and auth tokens",
            "Upload metadata database",
        ],
        "stride_hints": {
            "S": [
                "Attacker uploads files while impersonating another user "
                "via a stolen session token",
                "Forged upload requests sent with a victim's signed URL "
                "parameters",
            ],
            "T": [
                "Client-side MIME validation bypassed to upload a malicious "
                "script disguised as an image",
                "Stored file replaced or modified in transit to poison the "
                "thumbnail worker",
                "Upload metadata rows tampered with to point downloads at "
                "attacker files",
            ],
            "R": [
                "No audit log of who uploaded which file, so a malicious "
                "upload cannot be attributed",
                "Deletion events not logged, letting an insider deny wiping "
                "evidence",
            ],
            "I": [
                "Private uploads exposed when signed URL generation is "
                "predictable or URLs leak via referer headers",
                "Object storage bucket misconfigured as world-readable",
                "Error messages from the thumbnail worker leak internal "
                "paths",
            ],
            "D": [
                "Zip bombs or huge files exhaust worker memory despite the "
                "client-side size limit",
                "Flooding the upload endpoint saturates bandwidth for "
                "legitimate users",
            ],
            "E": [
                "Path traversal in the file name lets a user write outside "
                "their own directory",
                "Malicious file executed by the thumbnail worker with "
                "elevated privileges",
                "Download endpoint missing authorization checks lets one "
                "user fetch another user's private files",
            ],
        },
    },
    {
        "id": "sso-login-flow",
        "title": "SSO login flow",
        "description": (
            "Employees log in with a corporate identity provider over OIDC. "
            "The relying app stores session cookies, supports refresh "
            "tokens for the mobile app, and offers self-service password "
            "reset via emailed magic links. Failed logins are rate limited "
            "per IP."
        ),
        "assets": [
            "OIDC authorization codes and ID tokens",
            "Session cookies and refresh tokens",
            "Password-reset magic links",
            "Identity provider admin console",
            "Login audit logs",
        ],
        "stride_hints": {
            "S": [
                "Phishing page clones the login screen to harvest "
                "credentials and OTP codes",
                "Authorization code interception on a compromised redirect "
                "URI",
                "Session fixation: attacker plants a session cookie before "
                "the victim logs in",
            ],
            "T": [
                "Redirect URI or state parameter tampered with to send "
                "tokens to an attacker domain",
                "Magic link token in the email is altered to reset a "
                "different account",
            ],
            "R": [
                "Successful logins from unusual locations are not recorded, "
                "so account takeover cannot be proven",
                "Admin console actions lack immutable audit trails",
            ],
            "I": [
                "ID tokens logged in plain text by the relying app's "
                "request logger",
                "Password-reset emails expose whether an address is "
                "registered (user enumeration)",
                "Verbose error messages reveal which step of the login "
                "flow failed",
            ],
            "D": [
                "Credential-stuffing botnet locks out real users by "
                "triggering per-account lockouts",
                "Rate limiter keyed only on IP lets distributed attacks "
                "through",
            ],
            "E": [
                "Role claim in the ID token is client-controlled and never "
                "validated, granting admin access",
                "Password-reset flow lets an attacker change another user's "
                "password with a guessed token",
                "Refresh token scope is broader than the session it "
                "replaces",
            ],
        },
    },
    {
        "id": "public-api-keys",
        "title": "Public API with API keys",
        "description": (
            "A SaaS product exposes a REST API used by third-party "
            "integrations. Access uses long-lived API keys sent in a "
            "header, scoped per project with per-key rate limits. Keys can "
            "be created and revoked from a developer dashboard, and usage "
            "is billed per thousand requests."
        ),
        "assets": [
            "Long-lived API keys and their scopes",
            "Developer dashboard sessions",
            "Billing and usage metering records",
            "API gateway and rate limiter",
            "Customer data returned by endpoints",
        ],
        "stride_hints": {
            "S": [
                "Stolen API key replayed from a different IP with no "
                "device binding",
                "Attacker impersonates the dashboard to trick a developer "
                "into revealing a key",
            ],
            "T": [
                "Request parameters tampered with to access another "
                "project's resources (IDOR)",
                "Usage metering records altered to reduce a bill",
            ],
            "R": [
                "API calls are not logged with the key identity, so abuse "
                "cannot be attributed",
                "Key revocation events missing from the audit log",
            ],
            "I": [
                "API keys embedded in client-side JavaScript or committed "
                "to public repos",
                "Error responses echo back full request bodies including "
                "other tenants' data",
                "Verbose validation errors enumerate valid resource IDs",
            ],
            "D": [
                "Per-key rate limits are generous enough that one tenant "
                "can starve the shared gateway",
                "Expensive endpoints abused for computational DoS billed to "
                "the victim",
            ],
            "E": [
                "Key scope check happens only at creation, so a leaked "
                "read-only key can call admin endpoints",
                "Dashboard authorization flaw lets a user revoke another "
                "tenant's keys",
                "Scope upgrade possible by tampering with the dashboard "
                "request",
            ],
        },
    },
    {
        "id": "cicd-pipeline",
        "title": "CI/CD pipeline",
        "description": (
            "Engineers push to GitHub; a pipeline builds containers, runs "
            "tests, and deploys to Kubernetes. Third-party actions run on "
            "every pull request, build artifacts are pushed to a registry, "
            "and production deploys require one approval. Secrets live in "
            "the CI system's secret store."
        ),
        "assets": [
            "Source repositories and pull requests",
            "Build runners and container images",
            "CI secret store (cloud credentials, signing keys)",
            "Container registry and image tags",
            "Production Kubernetes cluster",
        ],
        "stride_hints": {
            "S": [
                "Attacker opens a malicious pull request from a fork to "
                "run code on trusted runners",
                "Compromised maintainer account pushes a backdoored commit "
                "that looks legitimate",
            ],
            "T": [
                "Build script or third-party action modified to inject "
                "malware into the container image",
                "Image tag in the registry overwritten so production "
                "pulls a trojaned build",
                "Pipeline definition tampered with to skip the approval "
                "gate",
            ],
            "R": [
                "Unsigned commits make it impossible to prove who "
                "introduced a malicious change",
                "Deploy approvals recorded only in chat, not in an "
                "immutable log",
            ],
            "I": [
                "CI secrets printed into build logs visible to all "
                "contributors",
                "Pull-request builds from forks exfiltrate secrets via "
                "egress to an attacker server",
            ],
            "D": [
                "Malicious pull request triggers expensive builds that "
                "exhaust the runner pool",
                "Registry filled with junk tags until storage quotas break "
                "deploys",
            ],
            "E": [
                "Runner executes with cloud credentials broader than the "
                "repo needs, letting a PR reach production",
                "Stolen CI secret used to push directly to the production "
                "registry",
                "Approval gate bypassed by editing the pipeline YAML in a "
                "feature branch",
            ],
        },
    },
    {
        "id": "mobile-app-backend",
        "title": "Mobile app backend",
        "description": (
            "A consumer mobile app talks to a JSON API over TLS. The app "
            "stores an OAuth access token on device, supports biometric "
            "unlock, and caches recent data locally. Push notifications go "
            "through a third-party provider, and the backend runs on "
            "auto-scaling VMs behind a load balancer."
        ),
        "assets": [
            "OAuth access tokens stored on device",
            "Locally cached user data",
            "Push notification service and device tokens",
            "Backend API and load balancer",
            "Biometric unlock gate",
        ],
        "stride_hints": {
            "S": [
                "Cloned app with a fake login screen harvests credentials "
                "before relaying them",
                "Attacker registers a device token for a victim's account "
                "to receive their pushes",
            ],
            "T": [
                "Man-in-the-middle with a sideloaded CA tampers with API "
                "responses on public Wi-Fi",
                "Local cache database modified to change balances or "
                "statuses shown in the UI",
            ],
            "R": [
                "In-app purchases or transfers logged only on device, so a "
                "user can deny making them",
                "No server-side record of which device performed an "
                "action",
            ],
            "I": [
                "Sensitive data cached unencrypted on the device and read "
                "by other apps or backups",
                "Push notification previews expose message content on the "
                "lock screen",
                "API returns more fields than the UI shows, leaking data "
                "to anyone sniffing traffic",
            ],
            "D": [
                "Token refresh endpoint hammered to lock the user out or "
                "burn backend quota",
                "Malformed payloads crash the app for everyone on an old "
                "version",
            ],
            "E": [
                "Jailbroken device bypasses the biometric gate and reads "
                "the stored token",
                "API trusts a client-supplied user ID header to authorize "
                "actions",
                "Debug build flags left enabled expose an admin screen in "
                "the shipped app",
            ],
        },
    },
    {
        "id": "pii-data-pipeline",
        "title": "PII data pipeline",
        "description": (
            "Customer records flow nightly from the app database through "
            "an ETL job into a data warehouse, then into an analytics "
            "dashboard. PII fields are supposed to be tokenized before "
            "they reach the warehouse, and analysts query the data with "
            "role-based access. Exports to CSV are allowed for reporting."
        ),
        "assets": [
            "Raw customer database with PII",
            "ETL job and tokenization step",
            "Data warehouse tables",
            "Analytics dashboard and user roles",
            "CSV exports and report files",
        ],
        "stride_hints": {
            "S": [
                "Attacker spoofs the ETL service identity to inject fake "
                "records into the warehouse",
                "Phished analyst credentials used to query the dashboard "
                "as a trusted employee",
            ],
            "T": [
                "Tokenization step disabled or misconfigured so raw PII "
                "lands in the warehouse",
                "ETL job logic altered to duplicate or drop records "
                "silently",
                "Dashboard query filters tampered with to widen the data "
                "returned",
            ],
            "R": [
                "No record of which analyst ran which query, so a data "
                "peek cannot be traced",
                "CSV exports not logged, making exfiltration "
                "undeniable",
            ],
            "I": [
                "Warehouse tables readable by every analyst regardless of "
                "role",
                "CSV exports emailed or stored on shared drives with raw "
                "PII",
                "Dashboard URL parameters leak query filters containing "
                "customer identifiers",
            ],
            "D": [
                "Runaway analyst query scans the full warehouse and slows "
                "the nightly ETL past its SLA",
                "Export job floods storage with repeated full-table CSV "
                "dumps",
            ],
            "E": [
                "Analyst role can be self-upgraded through the dashboard's "
                "role assignment bug",
                "ETL service account has write access to the raw database, "
                "letting a pipeline compromise alter source records",
                "Export permission bundled into the default viewer role",
            ],
        },
    },
]

_STOPWORDS = frozenset(
    "a an the and or of to in on for with is are be by as at from that this "
    "it its into over under without within via can could would should will "
    "have has had not no any all each other their there these those them "
    "they you your we our he she his her but if then than so such only just "
    "about out up down off when where what which who how why".split()
)


def get_scenario(sid: str) -> dict:
    """Return the scenario dict for a slug, or raise ValueError."""
    for scenario in SCENARIOS:
        if scenario["id"] == sid:
            return scenario
    raise ValueError(f"Unknown scenario: {sid!r}")


def _tokens(text: str) -> set[str]:
    words = re.findall(r"[a-z0-9]+", text.lower())
    return {w for w in words if w and w not in _STOPWORDS}


def _overlap(a: set[str], b: set[str]) -> float:
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def _matches_hint(user_text: str, hint: str, threshold: float = 0.3) -> bool:
    return _overlap(_tokens(user_text), _tokens(hint)) >= threshold


def score_threats(scenario_id: str, user_threats: list[dict]) -> dict:
    """Score a candidate's STRIDE threats against a scenario's hints.

    user_threats is a list of {"letter": "T", "text": "..."} dicts. A letter
    counts as covered when any user text for that letter shares meaningful
    keywords with any hint for the letter (token overlap >= 0.3), or when the
    user listed two or more threats for the letter. Returns a report dict
    with coverage, score, matched/missed hints, and feedback strings.
    """
    scenario = get_scenario(scenario_id)
    hints = scenario["stride_hints"]

    by_letter: dict[str, list[str]] = {letter: [] for letter in STRIDE}
    for threat in user_threats or []:
        letter = str(threat.get("letter", "")).strip().upper()
        text = str(threat.get("text", "")).strip()
        if letter in STRIDE and text:
            by_letter[letter].append(text)

    coverage: dict[str, bool] = {}
    matched_count = 0
    missed: dict[str, list[str]] = {}
    for letter, letter_hints in hints.items():
        texts = by_letter[letter]
        matched_hints = [
            hint
            for hint in letter_hints
            if any(_matches_hint(t, hint) for t in texts)
        ]
        matched_count += len(matched_hints)
        covered = bool(matched_hints) or len(texts) >= 2
        coverage[letter] = covered
        missed[letter] = [h for h in letter_hints if h not in matched_hints]

    total_hints = sum(len(v) for v in hints.values())
    covered_letters = sum(1 for v in coverage.values() if v)
    score = 100.0 * covered_letters / len(STRIDE)
    # small volume bonus: reward candidates who enumerate many threats
    total_threats = sum(len(v) for v in by_letter.values())
    score += min(10.0, max(0.0, (total_threats - covered_letters)) * 1.0)
    score = min(100.0, round(score, 1))

    feedback: list[str] = []
    for letter in STRIDE:
        name = STRIDE[letter]
        n = len(by_letter[letter])
        if coverage[letter]:
            feedback.append(
                f"{letter} ({name}): covered with {n} "
                f"threat{'s' if n != 1 else ''}."
            )
        else:
            feedback.append(
                f"{letter} ({name}): missing. Think about threats like: "
                f"{missed[letter][0] if missed[letter] else 'n/a'}"
            )

    return {
        "coverage": coverage,
        "score": score,
        "matched_hints": matched_count,
        "total_hints": total_hints,
        "missed": missed,
        "feedback": feedback,
    }


def _parse_threat_line(line: str) -> dict | None:
    match = re.match(r"^\s*([A-Za-z])\s*:\s*(.+?)\s*$", line)
    if not match:
        return None
    return {"letter": match.group(1).upper(), "text": match.group(2)}


def collect_threats(input_fn=input, print_fn=print) -> list[dict]:
    """Prompt for "L: description" threat lines until a blank line.

    Factored out of run_drill so it can be tested with a fake input_fn.
    """
    threats: list[dict] = []
    while True:
        line = input_fn("> ").rstrip("\n")
        if not line.strip():
            break
        parsed = _parse_threat_line(line)
        if parsed is None:
            print_fn(
                'Could not parse that line. Use the format "T: description", '
                "e.g. \"T: attacker tampers with the signed URL\"."
            )
            continue
        if parsed["letter"] not in STRIDE:
            print_fn(
                f"Unknown STRIDE letter {parsed['letter']!r}. "
                f"Valid letters: {', '.join(STRIDE)}."
            )
            continue
        threats.append(parsed)
    return threats


def run_drill(scenario_id: str | None = None,
              input_fn=input, print_fn=print) -> dict | None:
    """Run an interactive STRIDE threat-modeling drill.

    Lists scenarios when none is given, shows the chosen scenario's
    description and assets, collects "L: description" threat lines until a
    blank line, then prints the score report. Returns the report dict.
    """
    if scenario_id is None:
        print_fn("Pick a scenario:")
        for i, scenario in enumerate(SCENARIOS, 1):
            print_fn(f"  {i}. {scenario['title']} ({scenario['id']})")
        choice = input_fn("Number or id: ").strip()
        scenario = None
        for i, s in enumerate(SCENARIOS, 1):
            if choice == str(i) or choice == s["id"]:
                scenario = s
                break
        if scenario is None:
            print_fn(f"Unknown scenario: {choice!r}")
            return None
    else:
        scenario = get_scenario(scenario_id)

    print_fn(f"\n== {scenario['title']} ==\n")
    print_fn(scenario["description"])
    print_fn("\nAssets to protect:")
    for asset in scenario["assets"]:
        print_fn(f"  - {asset}")
    print_fn(
        "\nEnter one threat per line as \"LETTER: description\" "
        "(S/T/R/I/D/E). Blank line when done.\n"
        "Example: T: attacker bypasses client-side MIME validation to "
        "upload malware\n"
    )

    threats = collect_threats(input_fn=input_fn, print_fn=print_fn)
    report = score_threats(scenario["id"], threats)

    print_fn("\n-- Score report --")
    print_fn(f"Score: {report['score']}/100")
    print_fn(f"Hints matched: {report['matched_hints']}/{report['total_hints']}")
    for line in report["feedback"]:
        print_fn(f"  {line}")
    uncovered = [l for l, c in report["coverage"].items() if not c]
    if uncovered:
        print_fn("\nMissed hints for uncovered letters:")
        for letter in uncovered:
            print_fn(f"  {letter} ({STRIDE[letter]}):")
            for hint in report["missed"][letter]:
                print_fn(f"    - {hint}")
    return report
